### ISSUE TITLE
invalid code in JavaScript post

### ISSUE THREAD

**Issue by hr8** [pcattori/blog#2]
this post says JavaScript:

https://pedrocattori.dev/blog/go-like-channels-in-10-lines-of-javascript

but this is not JavaScript:

~~~js
async function compileBrowser(channel: WriteChannel<AssetsManifest>) {
~~~

specifically, JavaScript does not allow for type declarations in function signatures:

https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/function

**Comment by pcattori** [comment]
Anyone who wants JS can just omit the types, so I don't view this as an issue.

**Comment by hr8** [comment]
the blog post is loudly advertising that is it JavaScript:

> ![header](https://user-images.githubusercontent.com/121699587/216830469-eb059bf8-46db-4350-9bef-48f12d2e3a04.png)

which it is not:

~~~
function compileBrowser(channel: WriteChannel<AssetsManifest>) {}
Uncaught SyntaxError: missing ) after formal parameters
~~~

I dont know what language that is, but its not JavaScript.
